[package]
name = "ray-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
colored = "2.0"
fern = { version = "0.6", features = ["colored"] }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0.228"
toml = "0.9"
