[package]
name = "ray-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
log = "0.4"
ray-core = { path = "../ray-core" }
ray-driver = { path = "../ray-driver" }
ray-shared = { path = "../ray-shared" }
